CREATE TABLE SENSOR (
  SENSOR_ID   SERIAL PRIMARY KEY,
  DESCRIPTION VARCHAR(100)
);

CREATE TABLE DATA_TYPE (
  DATA_TYPE_ID SERIAL PRIMARY KEY,
  DESCRIPTION VARCHAR(20)
);

CREATE TABLE DATA (
  DATA_ID SERIAL PRIMARY KEY,
  VALUE         REAL NOT NULL,
  DATA_TYPE_ID  INTEGER NOT NULL,
  TIME          TIMESTAMP NOT NULL,
  SENSOR_ID     INTEGER NOT NULL,
  FOREIGN KEY (DATA_TYPE_ID) REFERENCES DATA_TYPE(DATA_TYPE_ID),
  FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(SENSOR_ID)
);

